name = "KeldyshContraction"
uuid = "da6be1f2-7f61-475e-9253-2fea1ca4beca"
authors = ["Orjan Ameye <orjan.ameye@hotmail.com>"]
version = "0.1.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NautyGraphs = "7509a0a4-015a-4167-b44b-0799a1a2605e"
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
Aqua = "0.8.11"
CheckConcreteStructs = "0.1"
Combinatorics = "1"
DocStringExtensions = "0.9.4"
Documenter = "1"
EnumX = "1"
ExplicitImports = "1.11"
Graphs = "1.13.1"
JET = "0.9.18, 0.10"
LaTeXStrings = "1.4"
Latexify = "0.16"
LinearAlgebra = "1.10"
Logging = "1.10"
MacroTools = "0.5.15"
NautyGraphs = "0.6"
OrderedCollections = "1"
Random = "1.10"
SmallCollections = "0.4.0, 0.5"
SymbolicUtils = "3.26"
TermInterface = "2"
Test = "1.10"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CheckConcreteStructs = "73c92db5-9da6-4938-911a-6443a7e94a58"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "CheckConcreteStructs", "ExplicitImports", "Test", "Aqua", "Random", "Documenter", "OrderedCollections", "Logging"]
